import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { ChangeEvent, useState, SyntheticEvent, useEffect } from 'react';
import axios from 'axios';

enum Status {
  Default = 'default',
  Generating = 'generating',
  Generated = 'generated',
}

export default function Home() {
  const [inputURL, setInputURL] = useState('');
  const [tinyUrl, setTinyUrl] = useState('');
  const [status, setStatus] = useState(Status.Default);

  function handleInputChange(event: ChangeEvent<HTMLInputElement>) {
    setInputURL(event.target.value);
  }

  async function handleUrlShorten(event: SyntheticEvent) {
    event.preventDefault();
    setStatus(Status.Generating);
    try {
      const result = await axios.post(`/api/url`, {
        url: inputURL,
      });

      setTinyUrl(`${process.env.NEXT_PUBLIC_BASE_URL}/${result.data.key}`);
    } catch (err) {
      console.error(err);
    }
  }

  useEffect(() => {
    if (tinyUrl.length > 0) {
      setStatus(Status.Generated);
    }
  }, [tinyUrl]);

  function getResult() {
    return status === Status.Generated
      ? tinyUrl
      : status === Status.Generating
      ? 'Generating...'
      : '';
  }

  return (
    <>
      <Head>
        <title>Tiny URL Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleUrlShorten}>
          <input type="text" value={inputURL} onChange={handleInputChange} />
          <button type="submit">Generate</button>
        </form>
        {<p data-testid="result">{getResult()}</p>}
      </main>
    </>
  );
}
