import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { ChangeEvent, useState } from 'react';

export default function Home() {
  const [inputURL, setInputURL] = useState('');

  function handleInputChange(event: ChangeEvent<HTMLInputElement>) {
    setInputURL(event.target.value);
  }
  return (
    <>
      <Head>
        <title>Tiny URL Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <input type="text" value={inputURL} onChange={handleInputChange} />
        </div>
      </main>
    </>
  );
}
